# Generated by Django 4.2.7 on 2024-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
