# Generated by Django 4.2.7 on 2024-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherfront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualweather',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
